'use strict';
export const listOfTeam = {
     "Andorra":"AD",
     "United Arab Emirates":"AE",
     "Afghanistan":"AF",
     "Antigua and Barbuda":"AG",
     "Anguilla":"AI",
     "Albania":"AL",
     "Armenia":"AM",
     "Angola":"AO",
     "Antarctica":"AQ",
     "Argentina":"AR",
     "American Samoa":"AS",
     "Austria":"AT",
     "Australia":"AU",
     "Aruba":"AW",
     "\u00c5land Islands":"AX",
     "Azerbaijan":"AZ",
     "Bosnia and Herzegovina":"BA",
     "Barbados":"BB",
     "Bangladesh":"BD",
     "Belgium":"BE",
     "Burkina Faso":"BF",
     "Bulgaria":"BG",
     "Bahrain":"BH",
     "Burundi":"BI",
     "Benin":"BJ",
     "Saint Barthélemy":"BL",
     "Bermuda":"BM",
     "Brunei Darussalam":"BN",
     "Brazil":"BR",
     "Bahamas":"BS",
     "Bhutan":"BT",
     "Bouvet Island":"BV",
     "Botswana":"BW",
     "Belarus":"BY",
     "Belize":"BZ",
     "Canada":"CA",
     "Congo":"CG",
     "Switzerland":"CH",
     "C\u00f4te d'Ivoire":"CI",
     "Cook Islands":"CK",
     "Chile":"CL",
     "Cameroon":"CM",
     "China":"CN",
     "Colombia":"CO",
     "Costa Rica":"CR",
     "Cuba":"CU",
     "Cape Verde":"CV",
     "Cura\u00e7ao":"CW",
     "Christmas Island":"CX",
     "Cyprus":"CY",
     "Czech Republic":"CZ",
     "Germany":"DE",
     "Djibouti":"DJ",
     "Denmark":"DK",
     "Dominica":"DM",
     "Dominican Republic":"DO",
     "Algeria":"DZ",
     "Ecuador":"EC",
     "Estonia":"EE",
     "Egypt":"EG",
     "Western Sahara":"EH",
     "Eritrea":"ER",
     "Spain":"ES",
     "Ethiopia":"ET",
     "Finland":"FI",
     "Fiji":"FJ",
   
     "Faroe Islands":"FO",
     "France":"FR",
     "Gabon":"GA",
     "United Kingdom":"GB",
     "Grenada":"GD",
     "Georgia":"GE",
     "French Guiana":"GF",
     "Guernsey":"GG",
     "Ghana":"GH",
     "Gibraltar":"GI",
     "Greenland":"GL",
     "Gambia":"GM",
     "Guinea":"GN",
     "Guadeloupe":"GP",
     "Equatorial Guinea":"GQ",
     "Greece":"GR",
     "Guatemala":"GT",
     "Guam":"GU",
     "Guinea-Bissau":"GW",
     "Guyana":"GY",
     "Hong Kong":"HK",
     "Honduras":"HN",
     "Croatia":"HR",
     "Haiti":"HT",
     "Hungary":"HU",
     "Indonesia":"ID",
     "Ireland":"IE",
     "Israel":"IL",
     "Isle of Man":"IM",
     "India":"IN",
     "Iraq":"IQ",
     "Iran, Islamic Republic of":"IR",
     "Iceland":"IS",
     "Italy":"IT",
     "Jersey":"JE",
     "Jamaica":"JM",
     "Jordan":"JO",
     "Japan":"JP",
     "Kenya":"KE",
     "Kyrgyzstan":"KG",
     "Cambodia":"KH",
     "Kiribati":"KI",
     "Comoros":"KM",

     "Kuwait":"KW",
     "Cayman Islands":"KY",
     "Kazakhstan":"KZ",
 
     "Lebanon":"LB",
     "Saint Lucia":"LC",
     "Liechtenstein":"LI",
     "Sri Lanka":"LK",
     "Liberia":"LR",
     "Lesotho":"LS",
     "Lithuania":"LT",
     "Luxembourg":"LU",
     "Latvia":"LV",
     "Libya":"LY",
     "Morocco":"MA",
     "Monaco":"MC",
     "Moldova, Republic of":"MD",
     "Montenegro":"ME",
     "Saint Martin":"MF",
     "Madagascar":"MG",
     "Marshall Islands":"MH",

     "Mali":"ML",
     "Myanmar":"MM",
     "Mongolia":"MN",
     "Macao":"MO",
     "Northern Mariana Islands":"MP",
     "Martinique":"MQ",
     "Mauritania":"MR",
     "Montserrat":"MS",
     "Malta":"MT",
     "Mauritius":"MU",
     "Maldives":"MV",
     "Malawi":"MW",
     "Mexico":"MX",
     "Malaysia":"MY",
     "Mozambique":"MZ",
     "Namibia":"NA",
     "New Caledonia":"NC",
     "Niger":"NE",
     "Norfolk Island":"NF",
     "Nigeria":"NG",
     "Nicaragua":"NI",
     "Netherlands":"NL",
     "Norway":"NO",
     "Nepal":"NP",
     "Nauru":"NR",
     "Niue":"NU",
     "New Zealand":"NZ",
     "Oman":"OM",
     "Panama":"PA",
     "Peru":"PE",
     "French Polynesia":"PF",
     "Papua New Guinea":"PG",
     "Philippines":"PH",
     "Pakistan":"PK",
     "Poland":"PL",
     "Saint Pierre and Miquelon":"PM",
    "Turkey": "TR",
    "England": "GB",
    "Portugal": "PT",
    "United States": "US",
    "Wales": "GB",
    "Sweden": "SE",
    "Serbia": "RS",
    "Ukraine": "UA",
    "Cote d'Ivoire": "CI",
    "Korea, South": "KR",
    "Bosnia-Herzegovina": "BA",
    "Uruguay": "UY"

};